# Database connection username and password
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWD:guest}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 9000

queue:
  order:
    name: ${ORDER_QUEUE:orders}
